// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package frontend

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Changelog() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div style=\"max-width: 700px;margin-left: auto; margin-right: auto;\"><div><h2>Changelog of WT-Heatmaps project</h2></div><div><h4>9 October 2026 23:30 GMT+3</h4><div>Fully purged non ground to ground kills from the dataset. Apparently stat table \"by BR\" never counted ground to begin with, fascinating, fixed.<br>Updated to carve version 3, including consistent logical team side indicator. All previous dataset records will have their team set to 0 as to not show up on.</div></div><div><h4>8 October 2026 23:30 GMT+3</h4><div>Made this changelog page.<br>Added arrows when area is being selected to indicate where kills are being made.<br>Reworked loading indicators.</div></div><div><h4>8 October 2026 13:30 GMT+3</h4><div>We can't have nice things, stop overloading my server.<br>Cloudflare protections are cranked due to influx from certain region.<br>API thrown into auth-only, it was a matter of time. Contact me to get a token.<br>Due to auth-only access it opens up prospects of making more custom endpoints.</div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
